Repository Rakshitg600/notakto-website, pull requests merged in 2025-08, with the labels that each got.

#46 refactor: use clsx for conditional classes
  package.json
  pnpm-lock.yaml
  src/app/liveMatch/page.tsx
  src/app/vsComputer/Board.tsx
  src/app/vsComputer/Cell.tsx
  src/app/vsPlayer/Board.tsx
  src/app/vsPlayer/Cell.tsx
  src/modals/BoardConfigModal.tsx
Labels: level 2, gssoc25, gssoc

#52 SEO: Add robots.txt file
  public/robots.txt
Labels: level 1, gssoc25, gssoc

#53 auto updates contributors images
  README.md
Labels: documentation, level 1, gssoc25, gssoc

#50 Feature : Replaced `alert()`s with Toasts for Better UX
  package.json
  pnpm-lock.yaml
  src/app/Menu.tsx
  src/app/layout.tsx
  src/app/liveMatch/page.tsx
  src/app/vsComputer/page.tsx
  src/components/ui/CustomToastContainer.tsx
  src/modals/PlayerNamesModal.tsx
Labels: level 2, gssoc25, gssoc, ui/ux

#67 Feature Request: Separate Toasts & Add Close Button
  src/app/Menu.tsx
  src/app/vsComputer/page.tsx
  src/components/hooks/useToastCooldown.ts
  src/components/ui/CustomToastContainer.tsx
  src/modals/PlayerNamesModal.tsx
Labels: level 2, gssoc25, gssoc, ui/ux

#72 refactor payment service
  .env.example
  .gitignore
  src/app/vsComputer/page.tsx
  src/services/payment.ts
Labels: refactor

#75 [REFACTOR] Added GameButton Component
  src/app/vsComputer/page.tsx
  src/app/vsPlayer/page.tsx
  src/components/ui/SettingButton.tsx
Labels: level 2, gssoc25, gssoc, refactor

#89 [REFACTOR] Added playerInput input
  src/components/ui/PlayerInput.tsx
  src/modals/BoardConfigModal.tsx
  src/modals/PlayerNamesModal.tsx
Labels: level 2, gssoc25, gssoc, refactor

#92 refactor : added board action button
  src/components/ui/BoardActionButton.tsx
  src/modals/BoardConfigModal.tsx
Labels: level 1, gssoc25, gssoc, refactor

#94 Refactor : Added new Difficulty Model Button and also structured the compoents
  src/app/Menu.tsx
  src/app/layout.tsx
  src/app/vsComputer/page.tsx
  src/app/vsPlayer/page.tsx
  src/components/ui/Buttons/BoardActionButton.tsx
  src/components/ui/Buttons/BoardConfigButton.tsx
  src/components/ui/Buttons/DifficultyActionButton.tsx
  src/components/ui/Buttons/MenuButton.tsx
  src/components/ui/Buttons/SettingButton.tsx
  src/components/ui/Buttons/WinnerButton.tsx
  src/components/ui/Inputs/PlayerInput.tsx
  src/components/ui/Toasts/CustomToastContainer.tsx
  src/modals/BoardConfigModal.tsx
  src/modals/DifficultyModal.tsx
  src/modals/PlayerNamesModal.tsx
  src/modals/WinnerModal.tsx
Labels: level 1, gssoc25, gssoc, refactor

#102 enhanced player's display text
  src/app/vsComputer/page.tsx
  src/app/vsPlayer/page.tsx
Labels: good first issue, beginner friendly, level 1, gssoc25, gssoc

#110 refactor the tutorial modal
  src/app/Menu.tsx
  src/app/page.tsx
Labels: good first issue, beginner friendly, level 1, gssoc25, gssoc, refactor

#107 [REFACTOR] Added Menu Container
  src/app/Menu.tsx
  src/app/page.tsx
  src/components/ui/Containers/Menu/MenuButtonContainer.tsx
  src/components/ui/Containers/Menu/MenuContainer.tsx
  src/components/ui/Containers/Menu/MenuLayout.tsx
  src/components/ui/Title/MenuTitle.tsx
Labels: level 2, gssoc25, gssoc, refactor
